Insert into Students values (1, 'Sanepa','Information Tech','stan.lee@gmail.com','Stan','Lee',9841312332);
Insert into Students values (2, 'Harisiddhi','Business','mike.stan@gmail.com','Mike','Stan',9841313560);
Insert into Students values (3, 'New Road','Commerce','ryan.hero@gmail.com','Ryan','Hero',9841313522);
Insert into Students values (4, 'Swayambhu','Aeorspace','joe.king@gmail.com','Joe','King',9801313335);

Insert into Users values (1,'admin','admin','admin');
Insert into Users values (2, 'student', 'student', 'student');
Insert into Users values (3, 'teacher', 'teacher', 'teacher');
Insert into Users values (4, 'root', 'root', 'root');

Insert into library (book_id,name,count,imageurl) values (1, 'Introduction to Programming',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (2, 'Introduction to Data Structure',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (3, 'Introduction to Algorithm',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (4, 'Introduction to Business',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (5, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (6, 'The Practice of Programming',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (7, 'The Art of Computer Programming',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (8, 'Close to the Machine',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (9, 'Fundamentals of Computer Algorithms',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (10, 'The Art of Unix Programming',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (11, 'The Java Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (12, 'The Best Software Writing I',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (13, 'The Best Software Writing II',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (14, 'The Best Software Writing III',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (15, 'The Best Software Writing IV',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (16, 'After the Software Wars',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (17, 'Free Software, Free Society',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (18, 'Patterns of Software',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (19, 'Clean Code',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (20, 'Algorithms Illuminated',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (21, 'Grace Hopper',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (22, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (23, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (24, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (25, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (26, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (27, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (28, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (29, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (30, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (31, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (32, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (33, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (34, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (35, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (36, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (37, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (38, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (39, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (40, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (41, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (42, 'The C++ Programming Language',100, 'assets/images/books/book.png');
Insert into library (book_id,name,count,imageurl) values (43, 'The C++ Programming Language',100, 'assets/images/books/book.png');
